name: pytorchGLM
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python==3.8
  - pip
  - scipy
  - numpy
  - pandas
  - matplotlib
  - xarray
  - ipykernel
  - tqdm
  - h5py
  - pytables
  - seaborn
  - ipywidgets
  - jupyter
  - jupyterlab
  - conda-forge::netCDF4
  - pytorch::pytorch=>1.9
  - pytorch::torchvision=>0.10
  - nvidia::cudatoolkit=>11.1
  - pip:
    - opencv-python
    - ray[default]
    - sklearn
    - test_tube
    - kornia
prefix: /home/eabe/anaconda3/envs/pytorchGLM
