wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.0
    start_time: 1635407395
    t:
      1:
      - 1
      - 5
      4: 3.8.0
      5: 0.12.6
      8:
      - 1
      - 5
